name: strop_app
description: Plataforma operativa de construccion
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.9.0
  flutter: ^3.35.0

dependencies:
  bloc: ^9.0.1
  cached_network_image: ^3.4.1
  connectivity_plus: ^7.0.0
  dio: ^5.9.0
  equatable: ^2.0.8
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_image_compress: ^2.4.0
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^3.1.0
  go_router: ^17.0.1
  image_picker: ^1.2.1
  intl: ^0.20.2
  json_annotation: ^4.9.0
  logger: ^2.6.2
  permission_handler: ^12.0.1
  shared_preferences: ^2.5.4
  sqflite: ^2.4.2
  supabase_flutter: ^2.12.0

dev_dependencies:
  bloc_test: ^10.0.0
  build_runner: ^2.7.1
  flutter_test:
    sdk: flutter
  freezed: ^3.2.3
  json_serializable: ^6.11.2
  mocktail: ^1.0.4
  very_good_analysis: ^10.0.0

flutter:
  generate: true
  uses-material-design: true
